version: '3.8'

services:
  amecssolarlogger:
    image: ghcr.io/yanorei32/amecs-solar-logger:latest@sha256:5f4aab6480e1bdfa4223ab92817e9df829904924dead7d967044584c570cfd0d
    hostname: amecssolarlogger
    container_name: amecssolarlogger__amecssolarlogger
    restart: unless-stopped

    environment:
      LAT: ${LAT}
      LON: ${LON}
      INFL_HOST: https://influxdb.yr32.net
      INFL_TOKEN: ${INFL_TOKEN}
      INFL_ORG: default
      INFL_BUCKET: power

    command: /usr/bin/amecs-solar-logger run

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: amecssolarlogger__default
