version: '3.8'

services:
  amecssolarlogger:
    image: ghcr.io/yanorei32/amecs-solar-logger:latest@sha256:4ffccae2adfc172669224dab593b086e7e318270ba6ae2211c2b2acb5b1c779c
    hostname: amecssolarlogger
    container_name: amecssolarlogger__amecssolarlogger
    restart: unless-stopped

    environment:
      LAT: ${LAT}
      LON: ${LON}
      INFL_HOST: https://influxdb.yr32.net
      INFL_TOKEN: ${INFL_TOKEN}
      INFL_ORG: default
      INFL_BUCKET: power

    command: /usr/bin/amecs-solar-logger run

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: amecssolarlogger__default
